on: [push]

env:
  REGISTRY_NAME: andescontainers
  CLUSTER_NAME: aks-cluster
  CLUSTER_RESOURCE_GROUP: grp-sitios-web-pre
  NAMESPACE: swpreprod
  SECRET: bRkhTwkuTkJS.D_Pt6gSSj40ujD6jWd0wL
  APP_NAME: sitioactions

name: AzureSWDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener C贸digo
        uses: actions/checkout@main

      - name: Conexi贸n Andes Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_NAME}}.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - run: |
          sh create.sh
          echo ${{secrets.REGISTRY_USERNAME}}
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/sitiosweb/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/sitiosweb/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Conexi贸n AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          cluster-name: ${{env.CLUSTER_NAME}}
          resource-group: ${{env.CLUSTER_RESOURCE_GROUP}}
      - name: Creaci贸n imagen
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          force: true
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
#extratest
