on: [push]

env:
  REGISTRY_NAME: andescontainers
  CLUSTER_NAME: aks-cluster
  CLUSTER_RESOURCE_GROUP: grp-sitios-web-pre
  NAMESPACE: swpreprod
  SECRET: bRkhTwkuTkJS.D_Pt6gSSj40ujD6jWd0wL
  APP_NAME: sitioactions

name: AzureSWDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener Código
        uses: actions/checkout@main

      - name: Conexión Andes Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_NAME}}.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - run: |
          az login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
          az acr login -n andescontainers.azurecr.io
          docker pull andescontainers.azurecr.io/sitiosweb/sw-jl-plantilla-facultades-alpine:1.0.0

#sh create.sh
#docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
#          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

#extra
